


//	Team object creations
	var austria = new team("Austria", 3, 0);
	var belgium = new team("Belgium", 1, 1);
	var bosnia = new team("Bosnia & Herz.", 2, 2);
	var bulgaria = new team("Bulgaria", 4, 3);
	var croatia = new team("Croatia", 2, 4);
	var czech = new team("Czech Republic", 3, 5);
	var denmark = new team("Denmark", 2, 6);
	var england = new team("England", 2, 7);
	var finland = new team("Finland", 4, 8);
	var france = new team("France", 1, 9);
	var germany = new team("Germany", 1, 10);
	var greece = new team("Greece", 2, 11);
	var hungary = new team("Hungary", 3, 12);
	var ireland = new team("Ireland", 4, 13);
	var israel = new team("Israel", 4, 14);
	var italy = new team("Italy", 1, 15);
	var montenegro = new team("Montenegro", 4, 16);
	var northernIreland = new team("N.Ireland", 4, 17);
	var netherlands = new team("Netherlands", 1, 18);
	var norway = new team("Norway", 4, 19);
	var poland = new team("Poland", 4, 20);
	var portugal = new team("Portugal", 2, 21);
	var romania = new team("Romania", 2, 22);
	var russia = new team("Russia", 2, 23);
	var scotland = new team("Scotland", 3, 24);
	var serbia = new team("Serbia", 3, 25);
	var slovakia = new team("Slovakia", 3, 26);
	var slovenia = new team("Slovenia", 3, 27);
	var spain = new team("Spain", 1, 28);
	var sweden = new team("Sweden", 3, 29);
	var switzerland = new team("Switzerland", 2, 30);
	var turkey = new team("Turkey", 3, 31);
	var ukraine = new team("Ukraine", 2, 32);
	var wales = new team("Wales", 4, 33);

	element = 0;
	var elementCounter = 0;
	var screenWidth = true;
	var zone = 'euro';
	

    var flagArray = new generate_flags(zone);
    var buttons = new buttons();
    var utils = new utils();
    var drawfull = new drawfull();
    var displayDraw = new displayDraw();


jQuery(function ($) {
	 
//	Function to pick random teams from each seed group & input into table
	$(document).ready(function() {
	
		drawfull.drawEuro();
		jQuery("#teamPicked").hide();
		jQuery("select").hide();

		$('select').change(function() { //take selected option


			pickedTeams = drawfull.drawnTeams; //had to assign to a new array. Causing issues (##need to find out why##)
			var optionSelected = $(this).find("option:selected");
			var valueSelected = optionSelected.val();
			var parsedValue = parseInt(valueSelected);
			var textSelected = optionSelected.text();

			checkSelect = valueSelected;



			//if team not in primary draw decide where to put team selected depending on their seed/seedgroup
			tablePos = 0;
			if (drawfull.allTeams[parsedValue].seedGroup == 1) {
				var x = utils.randNumber(100);
				if (x <= 70) {
					tablePos = utils.randTablePos(0, 3);
				} else if (x >= 71 && x <= 99) {
					tablePos = utils.randTablePos(4, 7);
				} else if (x == 100) {
					tablePos = utils.randTablePos(8, 11);
				} else {
					return false;
				}
			}

			if (drawfull.allTeams[parsedValue].seedGroup == 2) {
				var x = utils.randNumber(100);
				if (x <= 35) {
					tablePos = utils.randTablePos(0, 3);
				} else if (x >= 36 && x <= 90) {
					tablePos = utils.randTablePos(4, 7);
				} else if (x >= 91 && x <= 100) {
					tablePos = utils.randTablePos(8, 11);
				} else {
					return false;
				}
			}


			if (drawfull.allTeams[parsedValue].seedGroup == 3) {
				var x = utils.randNumber(100);
				if (x <= 7) {
					tablePos = utils.randTablePos(4, 7);
				} else if (x >= 8 && x <= 30) {
					tablePos = utils.randTablePos(8, 11);
				} else if (x >= 31 && x <= 100) {
					tablePos = utils.randTablePos(12, 15);
				} else {
					return false;
				}
			}

			if (drawfull.allTeams[parsedValue].seedGroup == 4) {
				var x = utils.randNumber(100);
				if (x <= 1) {
					tablePos = utils.randTablePos(8, 11);
				} else if (x >= 2 && x <= 100) {
					tablePos = utils.randTablePos(12, 15);
				} else {
					return false;
				}
			}

			//is team in the draw already? If it is highlight it if it isnt put into draw using table pos number generated by above.
			var inDraw = false;
			for (i = 0; i <= 15; i++) {
				if (textSelected == pickedTeams[i].name) {
					inDraw = true;
					$("td:contains('" + textSelected + "')").addClass("red");

				
				}

			};


			//flagValue = drawfull.allTeams[parsedValue].number;
			if (inDraw == false) {



			//*******bug needs fixing here. Flag dissapears when you have selected team. Intermitent.
              //  removedTeam = $('td').eq(tablePos).text();
				$('td').eq(tablePos).text(textSelected).prepend(flagArray.flagsG[drawfull.allTeams[parsedValue]]).addClass('red');
			}
            
            var newTeamArray = [];
            $("#tables").find("tr").each(function(){
                x = $(this).find('td.table').text();
                newTeamArray.push(x);

                for(i=0; i<=newTeamArray.length; i++) {
                    if (newTeamArray[i] == "") {
                        newTeamArray.splice(i, 1);
                    }
                }
            });
         
        

            displayDraw.displayseed(newTeamArray);

			$("select").hide();

			$(function() {
				$("#teamPicked").html("" + textSelected + " picked").show();
			});

			// event.stopPropagation(); //test if removal causes issues
            selectedTeam = drawfull.allTeams[parsedValue];

       

		});

		//select team from dynamically created select list
		$("#pickTeam").click(function() {
				buttons.createSelect();
		});

		//draw button
		$('#draw').click(function() {
			scroll();
			displayDraw.drawIndividual();

		});

		//draw all teams button
		$('#drawAll').click(function() {
			displayDraw.drawAllTeams();
		});

		//reset button
		$('#reset').click(function() {
			buttons.reset();
		});

		(function() {
			$("#pickTeam").show();
			$("select").hide();
		});

	});
});
